package com.slickapps.blackbird.exchanges;

public enum OperationType {
	CANCEL_ORDER, //
	PLACE_LIMIT_ORDER, //
	PLACE_MARKET_ORDER, //
	QUERY_EXCHANGE_INFO, //
	QUERY_FOR_QUOTE, //
	QUERY_OPEN_ORDERS_FOR_CURRENCY_PAIR, //
	QUERY_OPEN_ORDERS_FOR_ALL_CURRENCY_PAIRS, //
	QUERY_OPEN_POSITIONS, //
	QUERY_ORDER, //
	QUERY_ORDER_BOOK, //
	QUERY_ORDER_STATUS, //
	QUERY_TICKER, //
	QUERY_TRADE_HISTORY, //
	QUERY_WALLET, //
}